name: Build, Test, and Dockerize Spring Boot App

on:
  push:
    branches: [ main, ssstest ]
  pull_request:
    branches: [ main, ssstest ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    environment: myenv

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean package --no-transfer-progress

      - name: Run tests
        run: ./mvnw test --no-transfer-progress

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        # set envrionment to "myenv" in secrets
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t saiss07/banking-application-icici:latest .

      - name: Push Docker image
        run: |
          docker push saiss07/banking-application-icici:latest